name: se7ety
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  cloud_firestore: ^5.5.1
  device_preview: ^1.2.0
  firebase_auth: ^5.3.4
  firebase_core: ^3.8.1
  firebase_storage: ^12.3.7
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.16
  gap: ^3.0.1
  google_nav_bar: ^5.0.7
  image_picker: ^1.1.2
  intl: any
  lottie: ^3.2.0
  shared_preferences: ^2.3.3
  smooth_page_indicator: ^1.2.0+3
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Cairo-Regular.ttf
          weight: 400
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 500
